/**
 * patch_ml_worker.mjs — Injects pre-computed BRAND_ANCHORS into src/ml_worker.js
 *
 * Replaces the null-embedding BRAND_ANCHORS block with the real float arrays
 * generated by precompute_anchors_ort.mjs.
 *
 * Usage: node scripts/patch_ml_worker.mjs
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const mlWorkerPath = resolve(__dirname, '../src/ml_worker.js');
const snippetPath  = resolve(__dirname, 'anchor_snippet.js');

const mlWorker = readFileSync(mlWorkerPath, 'utf8');
const snippet  = readFileSync(snippetPath, 'utf8');

// Find the block between (and including) the BRAND_ANCHORS comment header and closing `};`
// The block starts at the comment "// Placeholder: these will be filled..." line
// and ends after the closing `};` of the BRAND_ANCHORS object.

const START_MARKER = '// Placeholder: these will be filled by the precompute script.';
const END_MARKER   = '};\n\n// ---------------------------------------------------------------------------\n// 4. Core Inference Functions';

const startIdx = mlWorker.indexOf(START_MARKER);
const endIdx   = mlWorker.indexOf(END_MARKER);

if (startIdx === -1) {
  console.error('❌ Could not find START_MARKER in ml_worker.js');
  console.error('   Looking for:', START_MARKER);
  process.exit(1);
}
if (endIdx === -1) {
  console.error('❌ Could not find END_MARKER in ml_worker.js');
  process.exit(1);
}

// Extract what we need
const before = mlWorker.slice(0, startIdx);
const after  = mlWorker.slice(endIdx);  // keeps the section-4 comment

// The snippet already contains the `const BRAND_ANCHORS = { ... };` block
// Strip the comment header lines from the snippet (keep only the const declaration)
const constIdx = snippet.indexOf('const BRAND_ANCHORS = {');
if (constIdx === -1) {
  console.error('❌ anchor_snippet.js does not contain `const BRAND_ANCHORS = {`');
  process.exit(1);
}
const anchorBlock = snippet.slice(constIdx);  // just the `const BRAND_ANCHORS = { ... };`

const patched = before + anchorBlock + '\n\n' + after;

writeFileSync(mlWorkerPath, patched, 'utf8');
console.log('✅ src/ml_worker.js patched with real 384-dim anchor embeddings');

// Verify: count how many embeddings are present
const matches = (patched.match(/new Float32Array\(\[/g) || []).length;
console.log(`   Float32Array instances found: ${matches} (expected: 15)`);
console.log('\n🚀 Now run: npm run build');
