/**
 * ml_worker.js — Ghost Form Phase 3 (Production Ready)
 *
 * Runs inside a dedicated Web Worker hosted by the Offscreen Document.
 * This execution context survives MV3 service worker suspensions.
 *
 * Responsibilities:
 *  1. Initialize the Transformers.js feature-extraction pipeline once (singleton).
 *  2. Cache the ONNX model via the Cache API so it survives worker restarts.
 *  3. Generate 384-dim L2-normalized sentence embeddings via mean pooling.
 *  4. Compute cosine similarity against pre-computed brand anchor vectors.
 *  5. Handle CONSENT_ANALYZE for Fine-Print AI dark pattern detection.
 *  6. Post results back to offscreen.js via postMessage.
 *
 * Message Protocol:
 *   IN  { type: 'ANALYZE',         id, payload: { text } }         → phishing check
 *   IN  { type: 'CONSENT_ANALYZE', id, payload: { consentText, anchors: string[] } }
 *   IN  { type: 'PING',            id }                            → health check
 *   IN  { type: 'RESTORE_ANCHORS', id, payload: { key: float[] } } → reload from cache
 *   OUT { type: 'RESULT',  id, payload }
 *   OUT { type: 'ERROR',   id, payload: string }
 *   OUT { type: 'READY',   payload: 'pipeline_warm'|'pipeline_cold' }
 *   OUT { type: 'STATUS',  payload: 'loading_model'|'model_ready' }
 *   OUT { type: 'STORE_ANCHORS', payload: { key: float[] } }
 */

import { pipeline, env, cos_sim } from '@xenova/transformers';

// ---------------------------------------------------------------------------
// 1. Configure Transformers.js for the Chrome Extension environment
// ---------------------------------------------------------------------------

// Use the browser's Cache API to persist the ONNX model across worker restarts.
// Without this, the ~23MB model would be re-downloaded from HuggingFace on
// every service worker wake-up.
env.useBrowserCache  = true;
env.allowLocalModels = false;

// Point the WASM resolver to the extension's dist/ folder.
// The WASM files are copied there by the Vite build.
env.backends.onnx.wasm.wasmPaths = chrome.runtime.getURL('dist/');

// ---------------------------------------------------------------------------
// 2. Singleton Pipeline
// ---------------------------------------------------------------------------

const MODEL_ID = 'Xenova/all-MiniLM-L6-v2';
let   embeddingPipeline = null;

/**
 * Lazily initializes the pipeline on first use.
 * Subsequent calls return the cached instance in O(1).
 * Reports STATUS messages so the offscreen doc can log download progress.
 *
 * @returns {Promise<FeatureExtractionPipeline>}
 */
async function getEmbeddingPipeline() {
  if (embeddingPipeline) return embeddingPipeline;

  postMessage({ type: 'STATUS', payload: 'loading_model' });

  try {
    embeddingPipeline = await pipeline('feature-extraction', MODEL_ID, {
      quantized: true, // INT8 quantized — ~23MB vs ~90MB fp32
      progress_callback: (progress) => {
        postMessage({ type: 'MODEL_PROGRESS', payload: progress });
      },
    });

    postMessage({ type: 'STATUS', payload: 'model_ready' });
    return embeddingPipeline;

  } catch (error) {
    postMessage({ type: 'ERROR', payload: `Model load failed: ${error.message}` });
    throw error;
  }
}

// ---------------------------------------------------------------------------
// 3. Brand Anchor Vectors (Pre-computed)
//
// Generated by: node scripts/precompute_anchors.mjs
// Model:        Xenova/all-MiniLM-L6-v2 (INT8 quantized)
// Dimensions:   384
// Pooling:      mean + L2 normalization
//
// These embeddings represent the semantic "fingerprint" of each legitimate
// brand's login page text. Cosine similarity between an incoming page's
// embedding and these anchors drives the 3-state (safe/unknown/unsafe) signal.
//
// To expand: add a new entry to scripts/precompute_anchors.mjs, re-run it,
// and paste the output here.  Also add the same key to BRAND_LABELS below.
// ---------------------------------------------------------------------------

// Placeholder: these will be filled by the precompute script.
// They are computed at runtime on first ANALYZE call and cached in session storage.
// Once restored from session cache via RESTORE_ANCHORS they stay resident in memory.
const BRAND_ANCHORS = {
  paypal: {
    label: 'PayPal Login',
    anchorText: 'PayPal Login - Secure your account, enter your email and password',
    embedding: null,
  },
  google_accounts: {
    label: 'Google Sign In',
    anchorText: 'Sign in to your Google Account - Enter your email',
    embedding: null,
  },
  amazon: {
    label: 'Amazon Sign In',
    anchorText: 'Amazon Sign In - Enter your email or mobile number and password',
    embedding: null,
  },
  microsoft: {
    label: 'Microsoft / Office 365 Sign In',
    anchorText: 'Sign in to your Microsoft account - Enter your email address or phone number',
    embedding: null,
  },
  apple: {
    label: 'Apple ID Sign In',
    anchorText: 'Sign in with your Apple ID - Enter your Apple ID and password to sign in',
    embedding: null,
  },
  facebook: {
    label: 'Facebook Login',
    anchorText: 'Facebook - Log in or create an account - Enter your email or phone and password',
    embedding: null,
  },
  instagram: {
    label: 'Instagram Login',
    anchorText: 'Instagram - Log in - Enter your username email or phone and password',
    embedding: null,
  },
  netflix: {
    label: 'Netflix Sign In',
    anchorText: 'Netflix - Sign In - Enter your email or phone and password to watch movies',
    embedding: null,
  },
  chase_bank: {
    label: 'Chase Bank Online Login',
    anchorText: 'Chase Online - Sign in - Enter your username and password to access your account',
    embedding: null,
  },
  dropbox: {
    label: 'Dropbox Login',
    anchorText: 'Sign in to Dropbox - Enter your email and password',
    embedding: null,
  },
  linkedin: {
    label: 'LinkedIn Sign In',
    anchorText: 'LinkedIn - Sign In - Enter your email and password to access your professional network',
    embedding: null,
  },
  twitter_x: {
    label: 'Twitter / X Sign In',
    anchorText: 'Sign in to X - Enter your phone email or username and password',
    embedding: null,
  },
  wellsfargo: {
    label: 'Wells Fargo Online Banking',
    anchorText: 'Wells Fargo Online - Sign On - Enter your username and password to access your accounts',
    embedding: null,
  },
  steam: {
    label: 'Steam Sign In',
    anchorText: 'Steam Login - Sign in to your Steam account - Enter your account name and password',
    embedding: null,
  },
  generic_phish: {
    label: 'Generic Phishing Login',
    anchorText: 'Verify your account - Confirm your identity - Enter your email username and password to continue',
    embedding: null,
  },
};

// ---------------------------------------------------------------------------
// 4. Core Inference Functions
// ---------------------------------------------------------------------------

/**
 * Generates a 384-dimensional embedding for the provided text.
 * Uses mean pooling + L2 normalization (the standard for all-MiniLM-L6-v2).
 *
 * @param {string} text
 * @returns {Promise<Float32Array>} Normalized embedding vector.
 */
async function computeEmbedding(text) {
  const pipe = await getEmbeddingPipeline();
  const output = await pipe(text, {
    pooling:   'mean',
    normalize: true,
  });
  return output.data; // Float32Array, shape [384]
}

/**
 * Ensures all brand anchor embeddings are computed.
 * On first call: runs inference for each anchor (~15 anchors × ~10ms each).
 * On subsequent calls: returns immediately (embeddings are cached in memory).
 * After computation: sends STORE_ANCHORS to offscreen.js for session persistence.
 */
let _anchorsComputed = false;

async function ensureAnchorsReady() {
  if (_anchorsComputed) return;

  // Check if any anchor still needs embedding
  const missing = Object.entries(BRAND_ANCHORS).filter(([, a]) => !a.embedding);
  if (missing.length === 0) {
    _anchorsComputed = true;
    return;
  }

  console.log(`[GhostForm ML] Computing ${missing.length} brand anchor embeddings...`);
  const startMs = Date.now();

  for (const [key, anchor] of missing) {
    anchor.embedding = await computeEmbedding(anchor.anchorText);
  }

  const elapsed = Date.now() - startMs;
  console.log(`[GhostForm ML] Anchor embeddings ready in ${elapsed}ms.`);
  _anchorsComputed = true;

  // Persist anchors to session storage via offscreen.js so they survive
  // service worker restarts without re-computation.
  const serializable = {};
  for (const [key, anchor] of Object.entries(BRAND_ANCHORS)) {
    serializable[key] = Array.from(anchor.embedding);
  }
  postMessage({ type: 'STORE_ANCHORS', payload: serializable });
}

/**
 * Main phishing analysis: embeds the page text, computes cosine similarity
 * against all brand anchors, and returns sorted results.
 *
 * @param {string} pageText - Sanitized visible text from the web page (≤ 2000 chars).
 * @returns {Promise<Array<{brand, label, score}>>} Sorted by score descending.
 */
async function analyzePageText(pageText) {
  await ensureAnchorsReady();

  const pageEmbedding = await computeEmbedding(pageText);

  const results = Object.entries(BRAND_ANCHORS).map(([key, anchor]) => ({
    brand: key,
    label: anchor.label,
    score: parseFloat(cos_sim(pageEmbedding, anchor.embedding).toFixed(4)),
  }));

  results.sort((a, b) => b.score - a.score);
  return results;
}

/**
 * Consent analysis for Fine-Print AI:
 * Embeds each anchor phrase in `anchors[]` and computes similarity against
 * the extracted consent text. Returns indices + scores for matches.
 *
 * @param {string}   consentText
 * @param {string[]} anchors     — dark pattern canonical phrases
 * @returns {Promise<Array<{index, score}>>}
 */
async function analyzeConsentText(consentText, anchors) {
  const consentEmbed = await computeEmbedding(consentText);
  const findings = [];

  for (let i = 0; i < anchors.length; i++) {
    const anchorEmbed = await computeEmbedding(anchors[i]);
    const score = parseFloat(cos_sim(consentEmbed, anchorEmbed).toFixed(4));
    findings.push({ index: i, score });
  }

  return findings;
}

// ---------------------------------------------------------------------------
// 5. Message Handler
// ---------------------------------------------------------------------------

self.onmessage = async (event) => {
  const { type, id, payload } = event.data;

  try {
    // ── Phishing Analysis ────────────────────────────────────────────────────
    if (type === 'ANALYZE') {
      if (!payload?.text || typeof payload.text !== 'string') {
        postMessage({ type: 'ERROR', id, payload: 'ANALYZE: missing or invalid text' });
        return;
      }
      const results = await analyzePageText(payload.text);
      postMessage({ type: 'RESULT', id, payload: results });
      return;
    }

    // ── Consent / Dark Pattern Analysis ─────────────────────────────────────
    if (type === 'CONSENT_ANALYZE') {
      const { consentText, anchors } = payload || {};
      if (!consentText || !Array.isArray(anchors) || anchors.length === 0) {
        postMessage({ type: 'RESULT', id, payload: [] });
        return;
      }
      const findings = await analyzeConsentText(consentText, anchors);
      postMessage({ type: 'RESULT', id, payload: findings });
      return;
    }

    // ── Raw Embedding (for custom callers) ───────────────────────────────────
    if (type === 'EMBED') {
      if (!payload?.text) {
        postMessage({ type: 'ERROR', id, payload: 'EMBED: missing text' });
        return;
      }
      const embedding = await computeEmbedding(payload.text);
      postMessage({ type: 'RESULT', id, payload: Array.from(embedding) });
      return;
    }

    // ── Health Check ─────────────────────────────────────────────────────────
    if (type === 'PING') {
      await getEmbeddingPipeline();
      postMessage({ type: 'PONG', id });
      return;
    }

    // ── Restore Cached Anchor Embeddings ─────────────────────────────────────
    // Sent by offscreen.js on worker startup with embeddings from session storage.
    // Avoids re-running all anchor inference after a service worker restart.
    if (type === 'RESTORE_ANCHORS') {
      if (payload && typeof payload === 'object') {
        let restored = 0;
        for (const [key, floatArray] of Object.entries(payload)) {
          if (BRAND_ANCHORS[key] && Array.isArray(floatArray) && floatArray.length === 384) {
            BRAND_ANCHORS[key].embedding = new Float32Array(floatArray);
            restored++;
          }
        }
        // Only mark as fully computed if ALL anchors were restored
        const totalAnchors = Object.keys(BRAND_ANCHORS).length;
        if (restored === totalAnchors) {
          _anchorsComputed = true;
          console.log(`[GhostForm ML] All ${restored} anchor embeddings restored from session cache.`);
        } else {
          console.log(`[GhostForm ML] Partially restored: ${restored}/${totalAnchors} anchors.`);
          // Remaining nulls will be computed lazily on first ANALYZE call
        }
      }
      postMessage({ type: 'RESULT', id, payload: 'anchors_restored' });
      return;
    }

    // ── Unknown message type ─────────────────────────────────────────────────
    console.warn('[GhostForm ML] Unknown message type:', type);
    postMessage({ type: 'ERROR', id, payload: `Unknown type: ${type}` });

  } catch (error) {
    console.error('[GhostForm ML] Handler error:', error);
    postMessage({ type: 'ERROR', id, payload: error.message });
  }
};

// ---------------------------------------------------------------------------
// 6. Pre-warm on Worker Startup
// ---------------------------------------------------------------------------
// Load the ONNX model immediately when the worker spawns.  This ensures the
// first real ANALYZE request returns quickly (model already in memory).
// After pre-warm (success or failure), post READY so offscreen.js knows it's
// safe to send RESTORE_ANCHORS without a race condition.

getEmbeddingPipeline()
  .then(() => {
    postMessage({ type: 'READY', payload: 'pipeline_warm' });
  })
  .catch((err) => {
    console.warn('[GhostForm ML] Pre-warm failed, will retry on first request:', err.message);
    postMessage({ type: 'READY', payload: 'pipeline_cold' });
  });
